services:
  # docs:
  #   container_name: docs
  #   build:
  #     context: .
  #     dockerfile: ./apps/docs/Dockerfile
  #   restart: always
  #   ports:
  #     - 3001:3001
  #   networks:
  #     - app_network
  commerce:
    container_name: commerce
    build:
      context: .
      dockerfile: ./apps/commerce/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
    image: ghcr.io/ssu-commerce/frontend/commerce:latest

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
