name: Release

on:
  push:
    branches:
      - feature/docker-publish

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Run
        run: |
          echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u ${{ secrets.USERNAME }} --password-stdins
          sudo docker compose up -d

      - name: Docker Push
        run: docker push ghcr.io/${{ env.REPO }}/commerce:latest
