import type { Metadata } from "next";
import StyledJsxRegistry from "./emotion";
import { ThemeProviders } from "./theme";
import styled from "./root.module.css";
import Layout from "../component/layout/layout";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="ko">
      <head></head>
      <body className={styled.body}>
        <StyledJsxRegistry>
          <ThemeProviders>
            <Layout>{children}</Layout>
          </ThemeProviders>
        </StyledJsxRegistry>
      </body>
      <div id="portal" />
    </html>
  );
}
