import type { Metadata } from "next";
import StyledJsxProvider from "provider/emotion";
import { ThemeProvider } from "provider/theme";
import styled from "./root.module.css";
import { ReactQueryProvider } from "provider/reactQuery";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export const RootLayout = ({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element => {
  return (
    <html lang="ko">
      <head />
      <body className={styled.body} suppressHydrationWarning>
        <ReactQueryProvider>
          <StyledJsxProvider>
            <ThemeProvider>
              {children}
              <div id="portal" />
            </ThemeProvider>
          </StyledJsxProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
};

export default RootLayout;
